### ISSUE TITLE
Is it Possible to Support the on_click Argument for st.download_button?

### ISSUE THREAD

**Issue by silocydata** [PaleNeutron/streamlit-ext#10]
What I require is to trigger a function when the user clicks on st.download_button.

The implementation would be like this:

st.download_button(
    label='title',
    data=virtual_workbook,
    file_name=f"BEPChecker_by_turboIFC {timestamp}.xlsx",
    mime=report_workbook.mime_type,
    `on_click=save_download_event`
)

If anyone has an idea on how to accomplish this, feel free to reply.

**Comment by PaleNeutron** [comment]
See here https://github.com/PaleNeutron/streamlit-ext/issues/8
