### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by alicjagrocholska** [PaleNeutron/streamlit-ext#2]
Hey PaleNeurtron! Thanks for this download_button, good work!+
One question, How can I set a download_button in dark mode (my page is all black, so I would like to customize it :)
Regards

**Comment by alicjagrocholska** [comment]
[here](https://discuss.streamlit.io/t/how-to-change-the-backgorund-color-of-button-widget/12103/25) they explain how to change color buttons, but it doesn't seem to work. I've been trying something like this:

```
st.markdown("""
<style>
div.stButton > button:first-child {
    background-color: #000000;
    color:#ffffff;
}
div.stButton > button:hover {
    background-color: #000000;
    color:#ff0000;
    }
</style>""", unsafe_allow_html=True)
```

Any ideas?

**Comment by PaleNeutron** [comment]
This is a limitation of [current implement](https://github.com/PaleNeutron/streamlit-ext/blob/2878579d1468a4ed1fca3584d537963a69be4365/streamlit_ext/st_ext.py#L99-L128). I'll update it to use the same class of `st.Button` ASAP.

**Comment by PaleNeutron** [comment]
A new release is created to resolve your problem，just see https://github.com/PaleNeutron/streamlit-ext/releases/tag/v0.1.5

**Comment by alicjagrocholska** [comment]
Great! Thanks a lot!
